#### Adattisztítás beadandó feladatok megoldása

In [149]:
input('Név:')

Név: Tamás Attila Csaba

'Tamás Attila Csaba'

In [150]:
input('Neptunkód:')

Neptunkód: IUZM8B

'IUZM8B'

#### Oldja meg a Python Pandas Dataframe (műveletek).pdf és a Python Pandas Dataframe (ETL).pdf végén levő feladatokat, majd töltse fel a Github-ra. 
#### FONTOS! Legalább 3-szor Commit-teljen!

In [1]:
#A megoldásokat a Coospace-re SajátNév1.ipynb névvel kell feltölteni.
#1. Hívja be az Ertekesites(nagyker).xlsx Lekérdezés1 munkalapját.
#2. Írassa ki az első 10 sort. Írassa ki az utolsó 5 sort. Írassa ki a 15 és 25 rekordok
#közötti sorokat.
#3. Készítsen egy táblát (dataframe) az első 20 dátumról, termékről és bevételről.
#4. Készítsen egy táblát a 10 legnagyobb nyereségű eladásról.
#5. Készítsen egy táblát az 5 legkisebb bevételű eladásról. Csak a dátum, város és a
#bevétel szerepeljen az oszlopban. A táblát mentse minbev.tsv, tabbal
#elválasztott fájlba.
#6. Keresse ki a 46464Ft nyereségű eladásokat.
#7. Írassa ki az Egerben és Hatvanban történt eladásokat.
#8. Írassa ki az 500000 fölötti eladásokat.
#9. Melyik volt a legnagyobb nyereségű eladás.
#10. Melyek voltak az átlagbevétel feletti eladások?

In [7]:
import pandas as pd
import os

print(os.getcwd())

C:\Users\User\Downloads\adattisztitas-beadando-2-Tamacsa

In [9]:
df=pd.read_excel('Ertekesites(nagyker).xlsx','Lekérdezés1')

In [10]:
df.head(10)

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
0,2015-01-02,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
1,2015-01-05,Iroda,Toll,800,320000,204800.0,115200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
2,2015-01-13,Játék,Labda,600,300000,240000.0,60000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
3,2015-01-16,Játék,Labda,600,300000,192000.0,108000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
4,2015-01-23,Játék,Labda,300,150000,120000.0,30000.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC
5,2015-01-24,Kert,Gereblye,400,280000,224000.0,56000.0,Nagy Kft,Heves,Gyöngyös,Pest,Gödöllő,2. ABC
6,2015-02-01,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
7,2015-02-12,Játék,Labda,600,300000,240000.0,60000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
8,2015-02-13,Iroda,Ceruza,800,240000,192000.0,48000.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,2. ABC
9,2015-02-14,Játék,Labda,900,450000,360000.0,90000.0,Kis Bt,Heves,Hatvan,Pest,Cegléd,2. ABC

In [11]:
df.tail(5)

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
301,2016-12-17,Kert,Kapa,1000,800000,640000.0,160000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
302,2016-12-17,Kert,Kapa,1000,800000,640000.0,160000.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,1. ABC
303,2016-12-19,Játék,Labda,900,450000,360000.0,90000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,1. ABC
304,2016-12-20,Iroda,Ceruza,1500,450000,360000.0,90000.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,1. ABC
305,2016-12-28,Iroda,Toll,800,320000,358400.0,-38400.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC

In [13]:
df.iloc[15:26]

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
15,2015-03-13,Játék,Kártya,500,250000,200000.0,50000.0,Nagy Kft,Heves,Gyöngyös,Pest,Cegléd,1. ABC
16,2015-03-15,Iroda,Ceruza,800,240000,268800.0,-28800.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,2. ABC
17,2015-03-16,Játék,Labda,900,450000,504000.0,-54000.0,Kis Bt,Heves,Hatvan,Pest,Cegléd,2. ABC
18,2015-03-23,Iroda,Ceruza,1100,330000,264000.0,66000.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
19,2015-03-24,Iroda,Toll,600,240000,192000.0,48000.0,Nagy Kft,Heves,Gyöngyös,Heves,Eger,1. ABC
20,2015-03-24,Iroda,Ceruza,800,240000,221184.0,18816.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,2. ABC
21,2015-04-01,Kert,Kapa,700,560000,448000.0,112000.0,Nagy Kft,Heves,Gyöngyös,Heves,Hatvan,1. ABC
22,2015-04-03,Játék,Labda,600,300000,240000.0,60000.0,Tóth Kft,Heves,Eger,Pest,Cegléd,1. ABC
23,2015-04-12,Játék,Kártya,500,250000,200000.0,50000.0,Nagy Kft,Heves,Gyöngyös,Pest,Cegléd,1. ABC
24,2015-04-16,Kert,Ásó,500,350000,280000.0,70000.0,Tóth Kft,Heves,Eger,Heves,Eger,1. ABC
25,2015-04-16,Kert,Gereblye,700,490000,392000.0,98000.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC

In [23]:
#3. Készítsen egy táblát (dataframe) az első 20 dátumról, termékről és bevételről.
elso_husz=df[['Dátum','Terméknév', 'Bevétel']].head(20)

In [22]:
 elso_husz

        Dátum Terméknév  Bevétel
0  2015-01-02      Toll   320000
1  2015-01-05      Toll   320000
2  2015-01-13     Labda   300000
3  2015-01-16     Labda   300000
4  2015-01-23     Labda   150000
5  2015-01-24  Gereblye   280000
6  2015-02-01      Toll   320000
7  2015-02-12     Labda   300000
8  2015-02-13    Ceruza   240000
9  2015-02-14     Labda   450000
10 2015-02-22     Labda   150000
11 2015-02-23  Gereblye   280000
12 2015-03-02      Kapa   560000
13 2015-03-03     Labda   150000
14 2015-03-04  Gereblye   280000
15 2015-03-13    Kártya   250000
16 2015-03-15    Ceruza   240000
17 2015-03-16     Labda   450000
18 2015-03-23    Ceruza   330000
19 2015-03-24      Toll   240000

In [24]:
#4. Készítsen egy táblát a 10 legnagyobb nyereségű eladásról.
top_tiz_legnagyobb_ny_eladas=df.nlargest(10,'Nyereség')
top_tiz_legnagyobb_ny_eladas

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
271,2016-10-14,Játék,Labda,2000,1000000,800000.0,200000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
272,2016-10-17,Játék,Labda,2000,1000000,800000.0,200000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
288,2016-11-13,Játék,Labda,2000,1000000,800000.0,200000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
59,2015-07-12,Kert,Ásó,1400,980000,784000.0,196000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,2. ABC
79,2015-08-11,Kert,Ásó,1400,980000,784000.0,196000.0,Kovács Bt,Pest,Gödöllő,Pest,Cegléd,1. ABC
139,2016-02-01,Kert,Ásó,1400,980000,784000.0,196000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
54,2015-06-27,Kert,Kapa,1200,960000,768000.0,192000.0,Szabó Rt,Pest,Monor,Heves,Eger,1. ABC
71,2015-07-27,Kert,Kapa,1200,960000,768000.0,192000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
111,2015-10-13,Kert,Kanna,1200,960000,768000.0,192000.0,Tóth Kft,Heves,Eger,Heves,Hatvan,1. ABC
216,2016-07-23,Kert,Kanna,1200,960000,768000.0,192000.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC

In [26]:
#5. Készítsen egy táblát az 5 legkisebb bevételű eladásról. Csak a dátum, város és a
#bevétel szerepeljen az oszlopban. A táblát mentse minbev.tsv, tabbal
#elválasztott fájlba.
ot_legkisebb_eladas=df.nsmallest(5,'Bevétel')
ot_legkisebb_eladas

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
297,2016-12-06,Iroda,Füzet,500,100000,112000.0,-12000.0,Kis Bt,Heves,Hatvan,Heves,Eger,1. ABC
300,2016-12-09,Iroda,Füzet,500,100000,80000.0,20000.0,Tóth Kft,Heves,Eger,Heves,Eger,1. ABC
33,2015-05-11,Iroda,Ceruza,400,120000,96000.0,24000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,2. ABC
34,2015-05-14,Iroda,Ceruza,400,120000,96768.0,23232.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,2. ABC
45,2015-06-10,Iroda,Ceruza,400,120000,134400.0,-14400.0,Kovács Bt,Pest,Gödöllő,Heves,Hatvan,1. ABC

In [28]:
#6. Keresse ki a 46464Ft nyereségű eladásokat.
hatos=df.loc[df['Nyereség']==46464]
hatos

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
166,2016-04-16,Iroda,Ceruza,800,240000,193536.0,46464.0,Kis Bt,Heves,Hatvan,Heves,Eger,2. ABC
183,2016-05-24,Iroda,Ceruza,800,240000,193536.0,46464.0,Kovács Bt,Pest,Gödöllő,Heves,Hatvan,1. ABC

In [32]:
#7. Írassa ki az Egerben és Hatvanban történt eladásokat.
hetes=df.loc[(df['Bolt város']=='Eger')|(df['Bolt város']=='Hatvan')]
hetes

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
0,2015-01-02,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
1,2015-01-05,Iroda,Toll,800,320000,204800.0,115200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
6,2015-02-01,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
12,2015-03-02,Kert,Kapa,700,560000,448000.0,112000.0,Nagy Kft,Heves,Gyöngyös,Heves,Hatvan,1. ABC
19,2015-03-24,Iroda,Toll,600,240000,192000.0,48000.0,Nagy Kft,Heves,Gyöngyös,Heves,Eger,1. ABC
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016-12-06,Játék,Labda,1000,500000,403200.0,96800.0,Kis Bt,Heves,Hatvan,Heves,Eger,1. ABC
297,2016-12-06,Iroda,Füzet,500,100000,112000.0,-12000.0,Kis Bt,Heves,Hatvan,Heves,Eger,1. ABC
298,2016-12-07,Iroda,Füzet,800,160000,128000.0,32000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,1. ABC
300,2016-12-09,Iroda,Füzet,500,100000,80000.0,20000.0,Tóth Kft,Heves,Eger,Heves,Eger,1. ABC
303,2016-12-19,Játék,Labda,900,450000,360000.0,90000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,1. ABC

In [36]:
#8. Írassa ki az 500000 fölötti eladásokat.
nyolcas=df.loc[df['Nyereség']>500000]
nyolcas

Empty DataFrame
Columns: [Dátum, Kategórianév, Terméknév, Mennyiség, Bevétel, Költség, Nyereség, Vevőnév, Vevő megye, Vevő város, Bolt megye, Bolt város, Boltnév]
Index: []

In [39]:
#9. Melyik volt a legnagyobb nyereségű eladás.
kilences=df[['Nyereség']].max()
kilences

Nyereség    200000.0
dtype: float64

In [43]:
#10. Melyek voltak az átlagbevétel feletti eladások?
tizes=df.loc[df['Nyereség']>df['Nyereség'].mean()]
tizes

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
0,2015-01-02,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
1,2015-01-05,Iroda,Toll,800,320000,204800.0,115200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
2,2015-01-13,Játék,Labda,600,300000,240000.0,60000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
3,2015-01-16,Játék,Labda,600,300000,192000.0,108000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
6,2015-02-01,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016-12-06,Játék,Labda,1000,500000,403200.0,96800.0,Kis Bt,Heves,Hatvan,Heves,Eger,1. ABC
301,2016-12-17,Kert,Kapa,1000,800000,640000.0,160000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
302,2016-12-17,Kert,Kapa,1000,800000,640000.0,160000.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,1. ABC
303,2016-12-19,Játék,Labda,900,450000,360000.0,90000.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,1. ABC
304,2016-12-20,Iroda,Ceruza,1500,450000,360000.0,90000.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,1. ABC

In [44]:
#11. Készítsen egy Ország nevű oszlopot és töltse fel Magyarországgal!
#12. Törölje a Vevő megye és Vevő város oszlopokat.
#13. Nevezze át a Bolt megye oszlopot Megyére.
#14. Módosítsa a 25 és 30 sor közötti eladások vevőit Kis bt-re15. Cserélje ki Bolt város oszlopban a Ceglédet Monorra.
#16. Írassa ki a bevételek és nyereségek átlagát és szórását.
#17. Kérdezze le a numerikus mezők statisztikai mutatóit.
#18. Írassa ki városonként az összbevételt és nyereséget.
#19. Írassa ki megyénként, azon belül kategóriánként a költségeket.
#20. Készítsen egy táblát a Heves megyei eladásokról. Melyik termékből volt a
#legnagyobb és legkisebb összmennyiségi eladás. A Vevők kategóriánként
#mennyit költöttek a boltokban?

In [47]:
df['Ország']='Magyarország'

In [49]:
#12. Törölje a Vevő megye és Vevő város oszlopokat.
modosított_df=df.drop(columns=['Vevő megye', 'Vevő város'])
modosított_df

,Dátum,Kategórianév,Terméknév,Mennyiség,Bevétel,Költség,Nyereség,Vevőnév,Bolt megye,Bolt város,Boltnév,Ország
0,2015-01-02,Iroda,Toll,800,320000,256000.0,64000.0,Kovács Bt,Heves,Eger,2. ABC,Magyarország
1,2015-01-05,Iroda,Toll,800,320000,204800.0,115200.0,Kovács Bt,Heves,Eger,2. ABC,Magyarország
2,2015-01-13,Játék,Labda,600,300000,240000.0,60000.0,Kovács Bt,Heves,Gyöngyös,1. ABC,Magyarország
3,2015-01-16,Játék,Labda,600,300000,192000.0,108000.0,Kovács Bt,Heves,Gyöngyös,1. ABC,Magyarország
4,2015-01-23,Játék,Labda,300,150000,120000.0,30000.0,Nagy Kft,Heves,Gyöngyös,1. ABC,Magyarország
...,...,...,...,...,...,...,...,...,...,...,...,...
301,2016-12-17,Kert,Kapa,1000,800000,640000.0,160000.0,Kovács Bt,Heves,Gyöngyös,1. ABC,Magyarország
302,2016-12-17,Kert,Kapa,1000,800000,640000.0,160000.0,Kis Bt,Heves,Gyöngyös,1. ABC,Magyarország
303,2016-12-19,Játék,Labda,900,450000,360000.0,90000.0,Kovács Bt,Heves,Eger,1. ABC,Magyarország
304,2016-12-20,Iroda,Ceruza,1500,450000,360000.0,90000.0,Kis Bt,Heves,Gyöngyös,1. ABC,Magyarország
305,2016-12-28,Iroda,Toll,800,320000,358400.0,-38400.0,Nagy Kft,Heves,Gyöngyös,1. ABC,Magyarország

In [54]:
#13. Nevezze át a Bolt megye oszlopot Megyére.
tizenharmas=df.rename(columns={'Bolt megye':'Megye'})
print(tizenharmas.dtypes)

Dátum           datetime64[ns]
Kategórianév            object
Terméknév               object
Mennyiség                int64
Bevétel                  int64
Költség                float64
Nyereség               float64
Vevőnév                 object
Vevő megye              object
Vevő város              object
Megye                   object
Bolt város              object
Boltnév                 object
Ország                  object
dtype: object

In [58]:
#14. Módosítsa a 25 és 30 sor közötti eladások vevőit Kis bt-re   
tizennegyes=df.loc[25:30,'Vevőnév']='Kis bt'
print(df.index[24:31])
print(df.loc[24:31])

RangeIndex(start=24, stop=31, step=1)
        Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
24 2015-04-16         Kert       Ásó        500   350000  280000.0   70000.0
25 2015-04-16         Kert  Gereblye        700   490000  392000.0   98000.0
26 2015-04-17        Játék    Kártya        700   350000  280000.0   70000.0
27 2015-04-22        Iroda    Ceruza       1100   330000  369600.0  -39600.0
28 2015-04-23         Kert      Kapa        700   560000  448000.0  112000.0
29 2015-04-24        Játék     Labda        500   250000  200000.0   50000.0
30 2015-04-27        Iroda    Ceruza       2000   600000  480000.0  120000.0
31 2015-05-03        Iroda     Füzet        700   140000  112000.0   28000.0

     Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév        Ország
24  Tóth Kft      Heves       Eger      Heves       Eger  1. ABC  Magyarország
25    Kis bt      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC  Magyarország
26    Kis bt      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC  Magyarország
27    Kis bt      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC  Magyarország
28    Kis bt      Heves   Gyöngyös      Heves       Eger  1. ABC  Magyarország
29    Kis bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC  Magyarország
30    Kis bt       Pest    Gödöllő      Heves     Hatvan  1. ABC  Magyarország
31  Tóth Kft      Heves       Eger       Pest     Cegléd  1. ABC  Magyarország

In [63]:
# 15. Cserélje ki Bolt város oszlopban a Ceglédet Monorra.
tizenotos=df.loc[df['Bolt város']=='Cegléd','Bolt város']='Monor'
print(len(df.loc[df['Bolt város']=='Cegléd','Bolt város']))
print(len(df.loc[df['Bolt város']=='Monor','Bolt város']))

0
46

In [68]:
#16. Írassa ki a bevételek és nyereségek átlagát és szórását.
tizenhatos=df[['Bevétel','Nyereség']].agg(['mean','std'])
tizenhatos

            Bevétel      Nyereség
mean  411437.908497  59011.450980
std   205394.201718  63144.279871

In [71]:
#17. Kérdezze le a numerikus mezők statisztikai mutatóit.
tizenhetes=df[['Mennyiség','Bevétel','Bevétel','Költség','Nyereség']].describe().round(4)
tizenhetes

       Mennyiség       Bevétel       Bevétel      Költség     Nyereség
count   306.0000      306.0000      306.0000     306.0000     306.0000
mean    849.0196   411437.9085   411437.9085  352426.4575   59011.4510
std     337.7103   205394.2017   205394.2017  172445.4360   63144.2799
min     300.0000   100000.0000   100000.0000   80000.0000  -97280.0000
25%     600.0000   250000.0000   250000.0000  225600.0000   24000.0000
50%     800.0000   400000.0000   400000.0000  327168.0000   68728.0000
75%    1000.0000   490000.0000   490000.0000  448000.0000   96000.0000
max    2000.0000  1000000.0000  1000000.0000  940032.0000  200000.0000

In [73]:
print(df.dtypes)

Dátum           datetime64[ns]
Kategórianév            object
Terméknév               object
Mennyiség                int64
Bevétel                  int64
Költség                float64
Nyereség               float64
Vevőnév                 object
Vevő megye              object
Vevő város              object
Bolt megye              object
Bolt város              object
Boltnév                 object
Ország                  object
dtype: object

In [109]:
#18. Írassa ki városonként az összbevételt és nyereséget.
tizennyolcas=df.groupby('Bolt város')
#for i,y in tizennyolcas:
#    print(i)
#    print(y)
print(tizennyolcas[['Bevétel','Nyereség']].sum().map(lambda x: f"{x:,.0f} Ft".replace(',','X').replace('.',',').replace('X','.')))

                  Bevétel      Nyereség
Bolt város
Eger        20.870.000 Ft  2.915.312 Ft
Gyöngyös    52.120.000 Ft  7.728.512 Ft
Gödöllő     18.990.000 Ft  2.113.264 Ft
Hatvan      16.470.000 Ft  2.876.080 Ft
Monor       17.450.000 Ft  2.424.336 Ft

In [108]:
#19. Írassa ki megyénként, azon belül kategóriánként a költségeket.
tizenkilences=df.groupby(['Bolt megye','Kategórianév'])['Költség'].sum()
print(tizenkilences.apply(lambda x: f"{x:,.0f} Ft".replace(',', 'X').replace('.', ',').replace('X', '.')))

Bolt megye  Kategórianév
Heves       Iroda           26.235.776 Ft
            Játék           17.940.288 Ft
            Kert            31.764.032 Ft
Pest        Iroda            7.989.376 Ft
            Játék            9.959.360 Ft
            Kert            13.953.664 Ft
Name: Költség, dtype: object

In [148]:
#20. Készítsen egy táblát a Heves megyei eladásokról. Melyik termékből volt a
#legnagyobb és legkisebb összmennyiségi eladás. A Vevők kategóriánként
#mennyit költöttek a boltokban?
heves_df=df[df['Bolt megye']=='Heves']
osszmennyiseg=heves_df.groupby('Terméknév')['Kategórianév'].sum()
legnagyobb_termek = osszmennyiseg.idxmax()
legkisebb_termek = osszmennyiseg.idxmin()
print(f"a legkisebb termék a {legkisebb_termek} és a legnagyobb termék {legnagyobb_termek}")


sum_df=heves_df.groupby('Kategórianév')['Bevétel'].sum()
max_df=heves_df.groupby('Kategórianév')[['Terméknév','Bevétel']].agg(['max','min'])
huszas = pd.concat([sum_df, max_df], axis=1)
szamos_oszlopok=huszas.select_dtypes(include=['number']).columns
huszas[szamos_oszlopok]=huszas[szamos_oszlopok].map(lambda x: f"{x:,.0f} Ft".replace('.', 'X').replace(',', '.').replace('X', ','))
huszas

a legkisebb termék a Füzet és a legnagyobb termék Ásó

,Bevétel,"(Terméknév, max)","(Terméknév, min)","(Bevétel, max)","(Bevétel, min)"
Kategórianév,,,,,
Iroda,30.250.000 Ft,Toll,Ceruza,600.000 Ft,100.000 Ft
Játék,21.210.000 Ft,Ugrókötél,Kártya,1.000.000 Ft,150.000 Ft
Kert,38.000.000 Ft,Ásó,Gereblye,980.000 Ft,350.000 Ft

In [ ]:
#1. Hívja be az Ertekesites(ETL).csv munkafüzetet, a dátumra figyeljen
#2. Az Egységár és a Érték oszlopot alakítsa egész típusúvá.
#3. Egyes oszlopokban hiányzó értékeket talál. Tegye velük ebben sorrendben a
#következőket:
#a) Ahol nincs érték a Mennyiségben, azt a sor törölje ki.
#b) A Kategórianév oszlopba kerüljön az „ismeretlen” szó.
#c) Az Egységár hiányzó értékeit töltse ki a terméknév segítségével.
#d) A Érték oszlop legyen az Egységár és a Mennyiség szorzata. Majd nevezze át Bevételnek.
#4. A Terméknév mezőben elütések vannak. Korrigálja őket
#5. A Mennyiség mezőben vannak elütések:
#a) Ahol negatív értékek vannak, ott legyen a Mennyiség az abszolút érték.
#b) Ahol 200-nál nagyobb Mennyiség van, ott legyen az előző és a következő rekord átlaga.
#6. Írassa ki az össze duplikációt. Majd szüntesse meg őket úgy, hogy az utolsó sor maradjon csak meg.
#7. Mentsen dataframe-t Javított.csv néven, ahol az elválasztó karakter a vessző.

In [2]:
#1. Hívja be az Ertekesites(ETL).csv munkafüzetet, a dátumra figyeljen
import pandas as pd

df_2=pd.read_csv('Ertekesites(ETL).csv', encoding='ISO-8859-2', delimiter=';')
print(df_2.dtypes)

Dátum            object
Kategórianév     object
Terméknév        object
Egységár         object
Mennyiség       float64
Érték            object
Vevőnév          object
Vevő megye       object
Vevő város       object
Bolt megye       object
Bolt város       object
Boltnév          object
dtype: object

In [3]:
df_2['Dátum']=pd.to_datetime(df_2['Dátum'])

In [4]:
print(df_2.dtypes)
df_2.head(5)

Dátum           datetime64[ns]
Kategórianév            object
Terméknév               object
Egységár                object
Mennyiség              float64
Érték                   object
Vevőnév                 object
Vevő megye              object
Vevő város              object
Bolt megye              object
Bolt város              object
Boltnév                 object
dtype: object

,Dátum,Kategórianév,Terméknév,Egységár,Mennyiség,Érték,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
0,2015-01-02,Iroda,Tol,"400,00 Ft",8.0,3 200 Ft,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
1,2015-01-13,Játék,Labda,"500,00 Ft",6.0,3 000 Ft,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
2,2015-01-23,Játék,Labda,"500,00 Ft",3.0,1 500 Ft,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC
3,2015-01-24,Kert,Gereblye,"700,00 Ft",-4.0,-2 800 Ft,Nagy Kft,Heves,Gyöngyös,Pest,Gödöllő,2. ABC
4,2015-02-02,Iroda,Toll,"400,00 Ft",8.0,3 200 Ft,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC

In [8]:
#2. Az Egységár és a Érték oszlopot alakítsa egész típusúvá.
def masodik_feladat(oszlop1: str, oszlop2: str, df: pd.DataFrame) -> pd.DataFrame:

    try:

        if not isinstance(oszlop1, str) or not isinstance(oszlop2, str):
            raise TypeError("Oszlopnév szöveg kell legyen!")
        
        if oszlop1 not in df.columns or oszlop2 not in df.columns:
            raise KeyError("Oszlop nem létezik!")

        df_clean = df_2.copy()

        df_clean[oszlop1] = df_clean[oszlop1].fillna('0')
        df_clean[oszlop2] = df_clean[oszlop2].fillna('0')

        
        df_clean[oszlop1] = df_clean[oszlop1].astype(str)
        df_clean[oszlop1] = df_clean[oszlop1].str.replace(',', '.')
        df_clean[oszlop1] = df_clean[oszlop1].str.replace(r'Ft', '', regex=True)
        df_clean[oszlop1] = df_clean[oszlop1].str.replace(r'[^\d.]', '', regex=True)
        
        df_clean[oszlop2] = df_clean[oszlop2].astype(str)  # ← KULCS! (hiányzott!)
        df_clean[oszlop2] = df_clean[oszlop2].str.replace(',', '.')
        df_clean[oszlop2] = df_clean[oszlop2].str.replace(r'[^\d.]', '', regex=True)
        

        
        df_clean[oszlop1] = pd.to_numeric(df_clean[oszlop1], errors='coerce').astype('Int64')
        df_clean[oszlop2] = pd.to_numeric(df_clean[oszlop2], errors='coerce').astype('Int64')
        
        
        return df_clean
    
    except (TypeError, KeyError) as e:
        print(f" Hiba: {e}")
        return None
    except Exception as e:
        print(f" Ismeretlen hiba: {type(e).__name__}: {e}")
        return None

df_clean = masodik_feladat("Egységár", "Érték", df_2)
df_2=df_clean

In [9]:
#3. Egyes oszlopokban hiányzó értékeket talál. Tegye velük ebben sorrendben a
#következőket:
#a) Ahol nincs érték a Mennyiségben, azt a sor törölje ki.
#b) A Kategórianév oszlopba kerüljön az „ismeretlen” szó.
#c) Az Egységár hiányzó értékeit töltse ki a terméknév segítségével.
#d) A Érték oszlop legyen az Egységár és a Mennyiség szorzata. Majd nevezze át Bevételnek.
for nan in df_2.columns:
    szamolas=df_2[nan].isna().sum()
    print(f" {nan} oszlopban {szamolas} hiányzó érték van")

#a)
df_2=df_2.dropna(subset=['Mennyiség'])

 Dátum oszlopban 0 hiányzó érték van
 Kategórianév oszlopban 5 hiányzó érték van
 Terméknév oszlopban 0 hiányzó érték van
 Egységár oszlopban 0 hiányzó érték van
 Mennyiség oszlopban 5 hiányzó érték van
 Érték oszlopban 0 hiányzó érték van
 Vevőnév oszlopban 0 hiányzó érték van
 Vevő megye oszlopban 0 hiányzó érték van
 Vevő város oszlopban 0 hiányzó érték van
 Bolt megye oszlopban 0 hiányzó érték van
 Bolt város oszlopban 0 hiányzó érték van
 Boltnév oszlopban 0 hiányzó érték van

In [10]:
for nan in df_2.columns:
    szamolas=df_2[nan].isna().sum()
    print(f" {nan} oszlopban {szamolas} hiányzó érték van")

 Dátum oszlopban 0 hiányzó érték van
 Kategórianév oszlopban 5 hiányzó érték van
 Terméknév oszlopban 0 hiányzó érték van
 Egységár oszlopban 0 hiányzó érték van
 Mennyiség oszlopban 0 hiányzó érték van
 Érték oszlopban 0 hiányzó érték van
 Vevőnév oszlopban 0 hiányzó érték van
 Vevő megye oszlopban 0 hiányzó érték van
 Vevő város oszlopban 0 hiányzó érték van
 Bolt megye oszlopban 0 hiányzó érték van
 Bolt város oszlopban 0 hiányzó érték van
 Boltnév oszlopban 0 hiányzó érték van

In [11]:
#b) A Kategórianév oszlopba kerüljön az „ismeretlen” szó.

df_2['Kategórianév']=df_2['Kategórianév'].fillna('Ismeretlen')
for nan in df_2.columns:
    szamolas=df_2[nan].isna().sum()
    print(f" {nan} oszlopban {szamolas} hiányzó érték van")

 Dátum oszlopban 0 hiányzó érték van
 Kategórianév oszlopban 0 hiányzó érték van
 Terméknév oszlopban 0 hiányzó érték van
 Egységár oszlopban 0 hiányzó érték van
 Mennyiség oszlopban 0 hiányzó érték van
 Érték oszlopban 0 hiányzó érték van
 Vevőnév oszlopban 0 hiányzó érték van
 Vevő megye oszlopban 0 hiányzó érték van
 Vevő város oszlopban 0 hiányzó érték van
 Bolt megye oszlopban 0 hiányzó érték van
 Bolt város oszlopban 0 hiányzó érték van
 Boltnév oszlopban 0 hiányzó érték van

C:\Users\User\AppData\Local\Temp\ipykernel_8620\1574354162.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Kategórianév']=df_2['Kategórianév'].fillna('Ismeretlen')

In [12]:
#c) Az Egységár hiányzó értékeit töltse ki a terméknév segítségével.
df_2['Egységár'] = df_2.groupby('Terméknév')['Egységár'].transform(
    lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan))
Missing_rows = df_2[df_2['Egységár'].isna()]
Missing_rows

C:\Users\User\AppData\Local\Temp\ipykernel_8620\3784273529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Egységár'] = df_2.groupby('Terméknév')['Egységár'].transform(

Empty DataFrame
Columns: [Dátum, Kategórianév, Terméknév, Egységár, Mennyiség, Érték, Vevőnév, Vevő megye, Vevő város, Bolt megye, Bolt város, Boltnév]
Index: []

##

In [13]:
#d) A Érték oszlop legyen az Egységár és a Mennyiség szorzata. Majd nevezze át Bevételnek.
df_2['Érték']=df_2['Egységár']*df_2['Mennyiség']
df_2=df_2.rename(columns={'Érték':'Bevétel'})
df_2

C:\Users\User\AppData\Local\Temp\ipykernel_8620\2799634075.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Érték']=df_2['Egységár']*df_2['Mennyiség']

,Dátum,Kategórianév,Terméknév,Egységár,Mennyiség,Bevétel,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
0,2015-01-02,Iroda,Tol,400,8.0,3200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
1,2015-01-13,Játék,Labda,500,6.0,3000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
2,2015-01-23,Játék,Labda,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC
3,2015-01-24,Kert,Gereblye,700,-4.0,-2800.0,Nagy Kft,Heves,Gyöngyös,Pest,Gödöllő,2. ABC
4,2015-02-02,Iroda,Toll,400,8.0,3200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
...,...,...,...,...,...,...,...,...,...,...,...,...
227,2017-12-06,Játék,Labda,500,6.0,3000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
228,2017-12-03,Kert,Ásó,700,5.0,3500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
229,2017-12-07,Kert,Ásó,700,5.0,3500.0,Tóth Kft,Heves,Eger,Heves,Eger,1. ABC
230,2017-12-12,Kert,Gereblye,700,9.0,6300.0,Tóth Kft,Heves,Eger,Heves,Gyöngyös,1. ABC
231,2017-12-14,Játék,Kártya,500,7.0,3500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC

In [14]:
for nan in df_2.columns:
    szamolas=df_2[nan].isna().sum()
    print(f" {nan} oszlopban {szamolas} hiányzó érték van")

 Dátum oszlopban 0 hiányzó érték van
 Kategórianév oszlopban 0 hiányzó érték van
 Terméknév oszlopban 0 hiányzó érték van
 Egységár oszlopban 0 hiányzó érték van
 Mennyiség oszlopban 0 hiányzó érték van
 Bevétel oszlopban 0 hiányzó érték van
 Vevőnév oszlopban 0 hiányzó érték van
 Vevő megye oszlopban 0 hiányzó érték van
 Vevő város oszlopban 0 hiányzó érték van
 Bolt megye oszlopban 0 hiányzó érték van
 Bolt város oszlopban 0 hiányzó érték van
 Boltnév oszlopban 0 hiányzó érték van

In [15]:
#4. A Terméknév mezőben elütések vannak. Korrigálja őket
#5. A Mennyiség mezőben vannak elütések:
#a) Ahol negatív értékek vannak, ott legyen a Mennyiség az abszolút érték.
#b) Ahol 200-nál nagyobb Mennyiség van, ott legyen az előző és a következő rekord átlaga.
#6. Írassa ki az össze duplikációt. Majd szüntesse meg őket úgy, hogy az utolsó sor maradjon csak meg.
#7. Mentsen dataframe-t Javított.csv néven, ahol az elválasztó karakter a vessző

In [16]:
#4. A Terméknév mezőben elütések vannak. Korrigálja őket
df_2['Terméknév'].unique()

array(['Tol', 'Labda', 'Gereblye', 'Toll', 'creuza', 'Kapa', 'Ásó',
       'Ceruza', 'cerza', 'Kártya', 'Ugrókötél', 'Kanna', 'Füzet',
       'Tolll'], dtype=object)

In [17]:
df_2.Terméknév=df_2.Terméknév.replace(['Tol','Tolll'],'Toll')
df_2.Terméknév=df_2.Terméknév.replace(['cerza','creuza'],'Ceruza')
df_2['Terméknév'].unique()

array(['Toll', 'Labda', 'Gereblye', 'Ceruza', 'Kapa', 'Ásó', 'Kártya',
       'Ugrókötél', 'Kanna', 'Füzet'], dtype=object)

In [18]:
#5. A Mennyiség mezőben vannak elütések:
#a) Ahol negatív értékek vannak, ott legyen a Mennyiség az abszolút érték.
df_2['Mennyiség']=df_2['Mennyiség'].abs()
df_2['Bevétel']=df_2['Bevétel'].abs()
df_2

,Dátum,Kategórianév,Terméknév,Egységár,Mennyiség,Bevétel,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
0,2015-01-02,Iroda,Toll,400,8.0,3200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
1,2015-01-13,Játék,Labda,500,6.0,3000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
2,2015-01-23,Játék,Labda,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC
3,2015-01-24,Kert,Gereblye,700,4.0,2800.0,Nagy Kft,Heves,Gyöngyös,Pest,Gödöllő,2. ABC
4,2015-02-02,Iroda,Toll,400,8.0,3200.0,Kovács Bt,Pest,Gödöllő,Heves,Eger,2. ABC
...,...,...,...,...,...,...,...,...,...,...,...,...
227,2017-12-06,Játék,Labda,500,6.0,3000.0,Kovács Bt,Pest,Gödöllő,Heves,Gyöngyös,1. ABC
228,2017-12-03,Kert,Ásó,700,5.0,3500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
229,2017-12-07,Kert,Ásó,700,5.0,3500.0,Tóth Kft,Heves,Eger,Heves,Eger,1. ABC
230,2017-12-12,Kert,Gereblye,700,9.0,6300.0,Tóth Kft,Heves,Eger,Heves,Gyöngyös,1. ABC
231,2017-12-14,Játék,Kártya,500,7.0,3500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC

In [19]:
#b) Ahol 200-nál nagyobb Mennyiség van, ott legyen az előző és a következő rekord átlaga.
elozo_kovetkezo_atlag=(df_2['Mennyiség'].shift(1)+df_2['Mennyiség'].shift(-1))/2
df_2.loc[df_2['Mennyiség']>200,'Mennyiség']=elozo_kovetkezo_atlag[df_2['Mennyiség']>200]

In [20]:
df_2.sort_values(by='Mennyiség', ascending=False, inplace=True)
df_2

,Dátum,Kategórianév,Terméknév,Egységár,Mennyiség,Bevétel,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
189,2017-06-14,Játék,Labda,500,20.0,10000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
199,2017-08-14,Játék,Labda,500,20.0,10000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,1. ABC
61,2016-01-27,Iroda,Ceruza,300,20.0,6000.0,Kovács Bt,Pest,Gödöllő,Heves,Hatvan,1. ABC
103,2016-07-24,Iroda,Ceruza,300,16.0,4800.0,Kis Bt,Heves,Hatvan,Heves,Gyöngyös,2. ABC
75,2016-04-26,Játék,Labda,500,16.0,8000.0,Nagy Kft,Heves,Gyöngyös,Pest,Gödöllő,2. ABC
...,...,...,...,...,...,...,...,...,...,...,...,...
188,2017-06-14,Játék,Kártya,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Pest,Kistarcsa,2. ABC
59,2016-01-23,Játék,Labda,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC
164,2017-02-14,Játék,Kártya,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Pest,Kistarcsa,2. ABC
55,2016-01-02,Játék,Labda,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Heves,Hatvan,1. ABC
2,2015-01-23,Játék,Labda,500,3.0,1500.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,1. ABC

In [21]:
#6. Írassa ki az össze duplikációt. Majd szüntesse meg őket úgy, hogy az utolsó sor maradjon csak meg.
df_2[df_2.duplicated(keep=False)]

,Dátum,Kategórianév,Terméknév,Egységár,Mennyiség,Bevétel,Vevőnév,Vevő megye,Vevő város,Bolt megye,Bolt város,Boltnév
113,2016-08-23,Kert,Kanna,800,12.0,9600.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
112,2016-08-23,Kert,Kanna,800,12.0,9600.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
16,2015-06-14,Játék,Labda,500,9.0,4500.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
17,2015-06-14,Játék,Labda,500,9.0,4500.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
15,2015-06-14,Játék,Labda,500,9.0,4500.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
162,2017-02-08,Iroda,Füzet,200,8.0,1600.0,Tóth Kft,Heves,Eger,Heves,Gyöngyös,2. ABC
161,2017-02-08,Iroda,Füzet,200,8.0,1600.0,Tóth Kft,Heves,Eger,Heves,Gyöngyös,2. ABC
214,2017-10-10,Kert,Gereblye,700,8.0,5600.0,Tóth Kft,Heves,Eger,Pest,Gödöllő,2. ABC
215,2017-10-10,Kert,Gereblye,700,8.0,5600.0,Tóth Kft,Heves,Eger,Pest,Gödöllő,2. ABC
32,2015-10-15,Játék,Labda,500,8.0,4000.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
31,2015-10-15,Játék,Labda,500,8.0,4000.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
175,2017-05-02,Kert,Kapa,800,7.0,5600.0,Kis Bt,Heves,Hatvan,Pest,Gödöllő,2. ABC
176,2017-05-02,Kert,Kapa,800,7.0,5600.0,Kis Bt,Heves,Hatvan,Pest,Gödöllő,2. ABC
73,2016-04-16,Kert,Gereblye,700,7.0,4900.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
72,2016-04-16,Kert,Gereblye,700,7.0,4900.0,Nagy Kft,Heves,Gyöngyös,Heves,Gyöngyös,2. ABC
202,2017-08-23,Iroda,Füzet,200,6.0,1200.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
193,2017-07-10,Kert,Kapa,800,6.0,4800.0,Tóth Kft,Heves,Eger,Heves,Gyöngyös,2. ABC
194,2017-07-10,Kert,Kapa,800,6.0,4800.0,Tóth Kft,Heves,Eger,Heves,Gyöngyös,2. ABC
201,2017-08-23,Iroda,Füzet,200,6.0,1200.0,Kis Bt,Heves,Hatvan,Pest,Kistarcsa,2. ABC
144,2016-12-11,Játék,Labda,500,6.0,3000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,2. ABC
145,2016-12-11,Játék,Labda,500,6.0,3000.0,Szabó Rt,Pest,Monor,Heves,Gyöngyös,2. ABC
177,2017-05-05,Játék,Ugrókötél,800,6.0,4800.0,Nagy Kft,Heves,Gyöngyös,Pest,Kistarcsa,1. ABC
178,2017-05-05,Játék,Ugrókötél,800,6.0,4800.0,Nagy Kft,Heves,Gyöngyös,Pest,Kistarcsa,1. ABC

In [22]:
len(df_2[df_2.duplicated()])

12

In [23]:
df_2=df_2.drop_duplicates()

In [24]:
len(df_2[df_2.duplicated()])

0

In [25]:
df_2[df_2.duplicated(keep=False)]

Empty DataFrame
Columns: [Dátum, Kategórianév, Terméknév, Egységár, Mennyiség, Bevétel, Vevőnév, Vevő megye, Vevő város, Bolt megye, Bolt város, Boltnév]
Index: []

In [26]:
#7. Mentsen dataframe-t Javított.csv néven, ahol az elválasztó karakter a vessző
df_2.sort_index(inplace=True)
for nan in df_2.columns:
    szamolas=df_2[nan].isna().sum()
    print(f" {nan} oszlopban {szamolas} hiányzó érték van")

 Dátum oszlopban 0 hiányzó érték van
 Kategórianév oszlopban 0 hiányzó érték van
 Terméknév oszlopban 0 hiányzó érték van
 Egységár oszlopban 0 hiányzó érték van
 Mennyiség oszlopban 0 hiányzó érték van
 Bevétel oszlopban 0 hiányzó érték van
 Vevőnév oszlopban 0 hiányzó érték van
 Vevő megye oszlopban 0 hiányzó érték van
 Vevő város oszlopban 0 hiányzó érték van
 Bolt megye oszlopban 0 hiányzó érték van
 Bolt város oszlopban 0 hiányzó érték van
 Boltnév oszlopban 0 hiányzó érték van

C:\Users\User\AppData\Local\Temp\ipykernel_8620\2810322419.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.sort_index(inplace=True)

In [27]:
df_2.to_csv('Javított.csv', sep=',', index=False, encoding='ISO-8859-2')

In [28]:
#vége

In [1]:
#A megoldásokat a Coospace-re SajátNév1.ipynb névvel kell feltölteni.

In [62]:
import pandas as pd

In [130]:
df=pd.read_excel('Ertekesites(nagyker).xlsx', 'Lekérdezés1')
print(df.head(10))
print(df.tail(5))
print(df[15:26])
datumok=df.sort_values('Dátum',ascending=True,ignore_index=True).head(20)
termekek=df.sort_values('Terméknév',ascending=True,ignore_index=True).head(20)
bevetel=df.sort_values('Bevétel',ascending=True,ignore_index=True).head(20)
print(datumok)
print(termekek)
print(bevetel)

       Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
0 2015-01-02        Iroda      Toll        800   320000  256000.0   64000.0
1 2015-01-05        Iroda      Toll        800   320000  204800.0  115200.0
2 2015-01-13        Játék     Labda        600   300000  240000.0   60000.0
3 2015-01-16        Játék     Labda        600   300000  192000.0  108000.0
4 2015-01-23        Játék     Labda        300   150000  120000.0   30000.0
5 2015-01-24         Kert  Gereblye        400   280000  224000.0   56000.0
6 2015-02-01        Iroda      Toll        800   320000  256000.0   64000.0
7 2015-02-12        Játék     Labda        600   300000  240000.0   60000.0
8 2015-02-13        Iroda    Ceruza        800   240000  192000.0   48000.0
9 2015-02-14        Játék     Labda        900   450000  360000.0   90000.0

     Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
0  Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
1  Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
2  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
3  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
4   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
5   Nagy Kft      Heves   Gyöngyös       Pest    Gödöllő  2. ABC
6  Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
7  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
8     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
9     Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
         Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
301 2016-12-17         Kert      Kapa       1000   800000  640000.0  160000.0
302 2016-12-17         Kert      Kapa       1000   800000  640000.0  160000.0
303 2016-12-19        Játék     Labda        900   450000  360000.0   90000.0
304 2016-12-20        Iroda    Ceruza       1500   450000  360000.0   90000.0
305 2016-12-28        Iroda      Toll        800   320000  358400.0  -38400.0

       Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
301  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
302     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  1. ABC
303  Kovács Bt       Pest    Gödöllő      Heves       Eger  1. ABC
304     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  1. ABC
305   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
        Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
15 2015-03-13        Játék    Kártya        500   250000  200000.0   50000.0
16 2015-03-15        Iroda    Ceruza        800   240000  268800.0  -28800.0
17 2015-03-16        Játék     Labda        900   450000  504000.0  -54000.0
18 2015-03-23        Iroda    Ceruza       1100   330000  264000.0   66000.0
19 2015-03-24        Iroda      Toll        600   240000  192000.0   48000.0
20 2015-03-24        Iroda    Ceruza        800   240000  221184.0   18816.0
21 2015-04-01         Kert      Kapa        700   560000  448000.0  112000.0
22 2015-04-03        Játék     Labda        600   300000  240000.0   60000.0
23 2015-04-12        Játék    Kártya        500   250000  200000.0   50000.0
24 2015-04-16         Kert       Ásó        500   350000  280000.0   70000.0
25 2015-04-16         Kert  Gereblye        700   490000  392000.0   98000.0

     Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
15  Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  1. ABC
16    Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
17    Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
18  Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
19  Nagy Kft      Heves   Gyöngyös      Heves       Eger  1. ABC
20    Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
21  Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
22  Tóth Kft      Heves       Eger       Pest     Cegléd  1. ABC
23  Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  1. ABC
24  Tóth Kft      Heves       Eger      Heves       Eger  1. ABC
25  Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
        Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
0  2015-01-02        Iroda      Toll        800   320000  256000.0   64000.0
1  2015-01-05        Iroda      Toll        800   320000  204800.0  115200.0
2  2015-01-13        Játék     Labda        600   300000  240000.0   60000.0
3  2015-01-16        Játék     Labda        600   300000  192000.0  108000.0
4  2015-01-23        Játék     Labda        300   150000  120000.0   30000.0
5  2015-01-24         Kert  Gereblye        400   280000  224000.0   56000.0
6  2015-02-01        Iroda      Toll        800   320000  256000.0   64000.0
7  2015-02-12        Játék     Labda        600   300000  240000.0   60000.0
8  2015-02-13        Iroda    Ceruza        800   240000  192000.0   48000.0
9  2015-02-14        Játék     Labda        900   450000  360000.0   90000.0
10 2015-02-22        Játék     Labda        300   150000  120000.0   30000.0
11 2015-02-23         Kert  Gereblye        400   280000  313600.0  -33600.0
12 2015-03-02         Kert      Kapa        700   560000  448000.0  112000.0
13 2015-03-03        Játék     Labda        300   150000  138240.0   11760.0
14 2015-03-04         Kert  Gereblye        400   280000  258048.0   21952.0
15 2015-03-13        Játék    Kártya        500   250000  200000.0   50000.0
16 2015-03-15        Iroda    Ceruza        800   240000  268800.0  -28800.0
17 2015-03-16        Játék     Labda        900   450000  504000.0  -54000.0
18 2015-03-23        Iroda    Ceruza       1100   330000  264000.0   66000.0
19 2015-03-24        Iroda      Toll        600   240000  192000.0   48000.0

      Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
0   Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
1   Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
2   Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
3   Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
4    Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
5    Nagy Kft      Heves   Gyöngyös       Pest    Gödöllő  2. ABC
6   Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
7   Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
8      Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
9      Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
10   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
11   Nagy Kft      Heves   Gyöngyös       Pest    Gödöllő  2. ABC
12   Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
13   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
14   Nagy Kft      Heves   Gyöngyös       Pest    Gödöllő  2. ABC
15   Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  1. ABC
16     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
17     Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
18   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
19   Nagy Kft      Heves   Gyöngyös      Heves       Eger  1. ABC
        Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
0  2016-08-12        Iroda    Ceruza        800   240000  192000.0   48000.0
1  2015-05-14        Iroda    Ceruza        400   120000   96768.0   23232.0
2  2016-04-15        Iroda    Ceruza       1200   360000  288000.0   72000.0
3  2016-03-23        Iroda    Ceruza        800   240000  268800.0  -28800.0
4  2016-12-20        Iroda    Ceruza       1500   450000  360000.0   90000.0
5  2016-01-26        Iroda    Ceruza        800   240000  268800.0  -28800.0
6  2015-05-22        Iroda    Ceruza       1400   420000  336000.0   84000.0
7  2015-12-17        Iroda    Ceruza       1200   360000  288000.0   72000.0
8  2015-05-25        Iroda    Ceruza       1400   420000  338688.0   81312.0
9  2015-05-27        Iroda    Ceruza       2000   600000  480000.0  120000.0
10 2015-06-03        Iroda    Ceruza        800   240000  268800.0  -28800.0
11 2015-06-10        Iroda    Ceruza        400   120000  134400.0  -14400.0
12 2015-11-17        Iroda    Ceruza       1200   360000  288000.0   72000.0
13 2016-10-24        Iroda    Ceruza       1500   450000  360000.0   90000.0
14 2015-06-21        Iroda    Ceruza       1400   420000  336000.0   84000.0
15 2015-11-02        Iroda    Ceruza       1500   450000  360000.0   90000.0
16 2015-10-27        Iroda    Ceruza       1400   420000  336000.0   84000.0
17 2016-10-27        Iroda    Ceruza       1500   450000  360000.0   90000.0
18 2015-10-06        Iroda    Ceruza       1500   450000  518400.0  -68400.0
19 2015-10-03        Iroda    Ceruza       1500   450000  360000.0   90000.0

      Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
0      Kis Bt      Heves     Hatvan      Heves       Eger  1. ABC
1   Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  2. ABC
2    Tóth Kft      Heves       Eger       Pest     Cegléd  1. ABC
3    Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
4      Kis Bt      Heves     Hatvan      Heves   Gyöngyös  1. ABC
5      Kis Bt      Heves     Hatvan       Pest     Cegléd  1. ABC
6    Tóth Kft      Heves       Eger      Heves       Eger  1. ABC
7    Tóth Kft      Heves       Eger      Heves     Hatvan  1. ABC
8    Tóth Kft      Heves       Eger      Heves       Eger  1. ABC
9   Kovács Bt       Pest    Gödöllő      Heves     Hatvan  1. ABC
10     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
11  Kovács Bt       Pest    Gödöllő      Heves     Hatvan  1. ABC
12   Tóth Kft      Heves       Eger      Heves     Hatvan  1. ABC
13   Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
14   Tóth Kft      Heves       Eger      Heves   Gyöngyös  2. ABC
15     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
16   Tóth Kft      Heves       Eger       Pest     Cegléd  1. ABC
17   Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
18     Kis Bt      Heves     Hatvan       Pest    Gödöllő  2. ABC
19     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
        Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
0  2016-12-09        Iroda     Füzet        500   100000   80000.0   20000.0
1  2016-12-06        Iroda     Füzet        500   100000  112000.0  -12000.0
2  2015-08-06        Iroda     Füzet        600   120000  117504.0    2496.0
3  2015-05-11        Iroda    Ceruza        400   120000   96000.0   24000.0
4  2016-10-23        Iroda     Füzet        600   120000   96000.0   24000.0
5  2016-10-26        Iroda     Füzet        600   120000   96000.0   24000.0
6  2015-05-14        Iroda    Ceruza        400   120000   96768.0   23232.0
7  2016-08-17        Iroda     Füzet        600   120000   96000.0   24000.0
8  2015-06-10        Iroda    Ceruza        400   120000  134400.0  -14400.0
9  2016-11-22        Iroda     Füzet        600   120000   96000.0   24000.0
10 2016-07-18        Iroda     Füzet        600   120000   96000.0   24000.0
11 2016-10-19        Iroda     Füzet        700   140000  112000.0   28000.0
12 2016-09-19        Iroda     Füzet        700   140000  112000.0   28000.0
13 2015-05-03        Iroda     Füzet        700   140000  112000.0   28000.0
14 2016-09-13        Játék    Kártya        300   150000  168000.0  -18000.0
15 2016-04-12        Játék     Labda        300   150000  168000.0  -18000.0
16 2016-08-17        Játék    Kártya        300   150000  146880.0    3120.0
17 2015-03-03        Játék     Labda        300   150000  138240.0   11760.0
18 2015-02-22        Játék     Labda        300   150000  120000.0   30000.0
19 2016-08-14        Játék    Kártya        300   150000  120000.0   30000.0

      Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
0    Tóth Kft      Heves       Eger      Heves       Eger  1. ABC
1      Kis Bt      Heves     Hatvan      Heves       Eger  1. ABC
2    Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
3   Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  2. ABC
4      Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
5      Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
6   Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  2. ABC
7    Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
8   Kovács Bt       Pest    Gödöllő      Heves     Hatvan  1. ABC
9      Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
10   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
11   Szabó Rt       Pest      Monor      Heves     Hatvan  1. ABC
12   Szabó Rt       Pest      Monor      Heves     Hatvan  1. ABC
13   Tóth Kft      Heves       Eger       Pest     Cegléd  1. ABC
14   Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  2. ABC
15     Kis Bt      Heves     Hatvan       Pest     Cegléd  1. ABC
16   Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  2. ABC
17   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
18   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
19   Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  2. ABC

In [131]:
legnagyobb_nyereseg=df.sort_values('Nyereség', ascending=False, ignore_index=True).head(10)
print(legnagyobb_nyereseg)
legkisebb_bevetel=df.sort_values('Bevétel',ascending=True, ignore_index=True).head(5)
legkisebb_bevetel=legkisebb_bevetel[['Dátum','Bolt város', 'Bevétel']]
mentes=legkisebb_bevetel.to_csv('minbev.tsv',sep='\t',encoding="ISO-8859-2")
mentes
konkret_nyereseg=df.loc[df['Nyereség']==46464]
print(konkret_nyereseg)
konkret_varos=df.loc[(df['Bolt város']=='Eger')|(df['Bolt város']=='Hatvan')]
print(konkret_varos)
konkret_bevetel=df.loc[df['Bevétel']>500000]
print(konkret_bevetel)
legnagyobb_nyereseg=df.loc[df['Nyereség']==df['Nyereség'].max()]
print(legnagyobb_nyereseg)
atlagbevetel_felettie_eladasok=df.loc[df['Bevétel']>df['Bevétel'].mean()]
print(atlagbevetel_felettie_eladasok)

       Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
0 2016-11-13        Játék     Labda       2000  1000000  800000.0  200000.0
1 2016-10-14        Játék     Labda       2000  1000000  800000.0  200000.0
2 2016-10-17        Játék     Labda       2000  1000000  800000.0  200000.0
3 2015-07-12         Kert       Ásó       1400   980000  784000.0  196000.0
4 2016-02-01         Kert       Ásó       1400   980000  784000.0  196000.0
5 2015-08-11         Kert       Ásó       1400   980000  784000.0  196000.0
6 2016-08-22         Kert     Kanna       1200   960000  768000.0  192000.0
7 2015-06-27         Kert      Kapa       1200   960000  768000.0  192000.0
8 2015-07-27         Kert      Kapa       1200   960000  768000.0  192000.0
9 2016-07-23         Kert     Kanna       1200   960000  768000.0  192000.0

     Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
0   Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
1   Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
2   Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
3  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  2. ABC
4   Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
5  Kovács Bt       Pest    Gödöllő       Pest     Cegléd  1. ABC
6   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
7   Szabó Rt       Pest      Monor      Heves       Eger  1. ABC
8   Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
9   Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
         Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
166 2016-04-16        Iroda    Ceruza        800   240000  193536.0   46464.0
183 2016-05-24        Iroda    Ceruza        800   240000  193536.0   46464.0

       Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
166     Kis Bt      Heves     Hatvan      Heves       Eger  2. ABC
183  Kovács Bt       Pest    Gödöllő      Heves     Hatvan  1. ABC
         Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
0   2015-01-02        Iroda      Toll        800   320000  256000.0   64000.0
1   2015-01-05        Iroda      Toll        800   320000  204800.0  115200.0
6   2015-02-01        Iroda      Toll        800   320000  256000.0   64000.0
12  2015-03-02         Kert      Kapa        700   560000  448000.0  112000.0
19  2015-03-24        Iroda      Toll        600   240000  192000.0   48000.0
..         ...          ...       ...        ...      ...       ...       ...
296 2016-12-06        Játék     Labda       1000   500000  403200.0   96800.0
297 2016-12-06        Iroda     Füzet        500   100000  112000.0  -12000.0
298 2016-12-07        Iroda     Füzet        800   160000  128000.0   32000.0
300 2016-12-09        Iroda     Füzet        500   100000   80000.0   20000.0
303 2016-12-19        Játék     Labda        900   450000  360000.0   90000.0

       Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
0    Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
1    Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
6    Kovács Bt       Pest    Gödöllő      Heves       Eger  2. ABC
12    Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
19    Nagy Kft      Heves   Gyöngyös      Heves       Eger  1. ABC
..         ...        ...        ...        ...        ...     ...
296     Kis Bt      Heves     Hatvan      Heves       Eger  1. ABC
297     Kis Bt      Heves     Hatvan      Heves       Eger  1. ABC
298  Kovács Bt       Pest    Gödöllő      Heves       Eger  1. ABC
300   Tóth Kft      Heves       Eger      Heves       Eger  1. ABC
303  Kovács Bt       Pest    Gödöllő      Heves       Eger  1. ABC

[97 rows x 13 columns]
         Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
12  2015-03-02         Kert      Kapa        700   560000  448000.0  112000.0
21  2015-04-01         Kert      Kapa        700   560000  448000.0  112000.0
28  2015-04-23         Kert      Kapa        700   560000  448000.0  112000.0
30  2015-04-27        Iroda    Ceruza       2000   600000  480000.0  120000.0
43  2015-05-27        Iroda    Ceruza       2000   600000  480000.0  120000.0
..         ...          ...       ...        ...      ...       ...       ...
274 2016-10-20         Kert      Kapa        700   560000  451584.0  108416.0
280 2016-11-02         Kert     Kanna        700   560000  448000.0  112000.0
288 2016-11-13        Játék     Labda       2000  1000000  800000.0  200000.0
301 2016-12-17         Kert      Kapa       1000   800000  640000.0  160000.0
302 2016-12-17         Kert      Kapa       1000   800000  640000.0  160000.0

       Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
12    Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
21    Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
28    Nagy Kft      Heves   Gyöngyös      Heves       Eger  1. ABC
30   Kovács Bt       Pest    Gödöllő      Heves     Hatvan  1. ABC
43   Kovács Bt       Pest    Gödöllő      Heves     Hatvan  1. ABC
..         ...        ...        ...        ...        ...     ...
274   Nagy Kft      Heves   Gyöngyös       Pest     Cegléd  1. ABC
280     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  2. ABC
288   Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
301  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
302     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  1. ABC

[72 rows x 13 columns]
         Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
271 2016-10-14        Játék     Labda       2000  1000000  800000.0  200000.0
272 2016-10-17        Játék     Labda       2000  1000000  800000.0  200000.0
288 2016-11-13        Játék     Labda       2000  1000000  800000.0  200000.0

      Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
271  Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
272  Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
288  Szabó Rt       Pest      Monor      Heves   Gyöngyös  1. ABC
         Dátum Kategórianév Terméknév  Mennyiség  Bevétel   Költség  Nyereség  \
9   2015-02-14        Játék     Labda        900   450000  360000.0   90000.0
12  2015-03-02         Kert      Kapa        700   560000  448000.0  112000.0
17  2015-03-16        Játék     Labda        900   450000  504000.0  -54000.0
21  2015-04-01         Kert      Kapa        700   560000  448000.0  112000.0
25  2015-04-16         Kert  Gereblye        700   490000  392000.0   98000.0
..         ...          ...       ...        ...      ...       ...       ...
296 2016-12-06        Játék     Labda       1000   500000  403200.0   96800.0
301 2016-12-17         Kert      Kapa       1000   800000  640000.0  160000.0
302 2016-12-17         Kert      Kapa       1000   800000  640000.0  160000.0
303 2016-12-19        Játék     Labda        900   450000  360000.0   90000.0
304 2016-12-20        Iroda    Ceruza       1500   450000  360000.0   90000.0

       Vevőnév Vevő megye Vevő város Bolt megye Bolt város Boltnév
9       Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
12    Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
17      Kis Bt      Heves     Hatvan       Pest     Cegléd  2. ABC
21    Nagy Kft      Heves   Gyöngyös      Heves     Hatvan  1. ABC
25    Nagy Kft      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
..         ...        ...        ...        ...        ...     ...
296     Kis Bt      Heves     Hatvan      Heves       Eger  1. ABC
301  Kovács Bt       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
302     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  1. ABC
303  Kovács Bt       Pest    Gödöllő      Heves       Eger  1. ABC
304     Kis Bt      Heves     Hatvan      Heves   Gyöngyös  1. ABC

[139 rows x 13 columns]

In [132]:
#Feladatok

In [133]:
df['Ország']='Magyarország'
df=df.drop(columns=['Vevő város','Vevő megye'])
df=df.rename(columns={'Bolt megye':'Megye'})
df['Bolt város']=df['Bolt város'].replace({'Cegléd':'Monor'})

In [134]:
df.loc[25:31,'Vevőnév']='Kis bt'
bevetelek_nyeresegek=df[['Bevétel','Nyereség']].describe()
print(bevetelek_nyeresegek)
print(df.describe())

              Bevétel       Nyereség
count      306.000000     306.000000
mean    411437.908497   59011.450980
std     205394.201718   63144.279871
min     100000.000000  -97280.000000
25%     250000.000000   24000.000000
50%     400000.000000   68728.000000
75%     490000.000000   96000.000000
max    1000000.000000  200000.000000
                               Dátum    Mennyiség         Bevétel  \
count                            306   306.000000      306.000000
mean   2016-02-07 12:18:49.411764736   849.019608   411437.908497
min              2015-01-02 00:00:00   300.000000   100000.000000
25%              2015-08-07 00:00:00   600.000000   250000.000000
50%              2016-03-21 12:00:00   800.000000   400000.000000
75%              2016-08-08 18:00:00  1000.000000   490000.000000
max              2016-12-28 00:00:00  2000.000000  1000000.000000
std                              NaN   337.710255   205394.201718

             Költség       Nyereség
count     306.000000     306.000000
mean   352426.457516   59011.450980
min     80000.000000  -97280.000000
25%    225600.000000   24000.000000
50%    327168.000000   68728.000000
75%    448000.000000   96000.000000
max    940032.000000  200000.000000
std    172445.436005   63144.279871

In [142]:
ossz_bev=df.groupby('Bolt város')['Bevétel'].sum()
ossz_nyer=df.groupby('Bolt város')['Nyereség'].sum()
print(ossz_nyer,ossz_bev)
#19. Írassa ki megyénként, azon belül kategóriánként a költségeket.
megye_kat_kolts=df.groupby(['Megye','Kategórianév'])['Költség'].mean()
print(megye_kat_kolts)

Bolt város
Eger        2915312.0
Gyöngyös    7728512.0
Gödöllő     2113264.0
Hatvan      2876080.0
Monor       2424336.0
Name: Nyereség, dtype: float64 Bolt város
Eger        20870000
Gyöngyös    52120000
Gödöllő     18990000
Hatvan      16470000
Monor       17450000
Name: Bevétel, dtype: int64
Megye  Kategórianév
Heves  Iroda           265007.838384
       Játék           320362.285714
       Kert            512323.096774
Pest   Iroda           266312.533333
       Játék           331978.666667
       Kert            481160.827586
Name: Költség, dtype: float64

In [148]:
#20. Készítsen egy táblát a Heves megyei eladásokról. Melyik termékből volt a
#legnagyobb és legkisebb összmennyiségi eladás. A Vevők kategóriánként
#mennyit költöttek a boltokban?
legkisebb_termek_eladas=df.loc[df['Megye']=='Heves'].groupby('Terméknév')['Mennyiség'].sum().head(1)
legnagyobb_termek_eladas=df.loc[df['Megye']=='Heves'].groupby('Terméknév')['Mennyiség'].sum().tail(1)
print(legkisebb_termek_eladas,legnagyobb_termek_eladas)

Terméknév
Ceruza    47900
Name: Mennyiség, dtype: int64 Terméknév
Ásó    19100
Name: Mennyiség, dtype: int64

Terméknév
Ceruza    47900
Name: Mennyiség, dtype: int64

In [1]:
import pandas as pd

In [80]:
df=pd.read_csv(filepath_or_buffer='Ertekesites(ETL).csv',
               delimiter=';',
               encoding='ISO-8859-2'
              )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dátum         232 non-null    object
 1   Kategórianév  227 non-null    object
 2   Terméknév     232 non-null    object
 3   Egységár      227 non-null    object
 4   Mennyiség     227 non-null    float64
 5   Érték         218 non-null    object
 6   Vevőnév       232 non-null    object
 7   Vevő megye    232 non-null    object
 8   Vevő város    232 non-null    object
 9   Bolt megye    232 non-null    object
 10  Bolt város    232 non-null    object
 11  Boltnév       232 non-null    object
dtypes: float64(1), object(11)
memory usage: 21.9+ KB

In [81]:
 #2. Az Egységár és a Érték oszlopot alakítsa egész típusúvá.
df['Egységár']=df['Egységár'].astype(str)
df['Érték']=df['Érték'].astype(str)

In [82]:
df['Egységár']=df['Egységár'].str.replace(',','.')
df['Egységár']=df['Egységár'].str.replace('Ft','',regex=False)
df['Érték']=df['Érték'].str.replace('Ft','',regex=False)
df['Érték']=df['Érték'].str.replace(' ','',regex=False)

In [83]:
df['Érték']=pd.to_numeric(df['Érték'],errors='coerce').astype('int64',errors='ignore')
df['Egységár']=pd.to_numeric(df['Egységár'],errors='coerce').astype('int64',errors='ignore')

In [84]:
df['Érték']=df['Érték'].convert_dtypes(convert_integer=True)
df['Egységár']=df['Egységár'].convert_dtypes(convert_integer=True)
df['Érték'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 232 entries, 0 to 231
Series name: Érték
Non-Null Count  Dtype
--------------  -----
218 non-null    Int64
dtypes: Int64(1)
memory usage: 2.2 KB

In [104]:
df=df.dropna(subset=['Mennyiség'])
print(df['Mennyiség'].isna().sum())
df=df.fillna(value={'Kategórianév':'ismeretlen'})
print(df['Kategórianév'].isna().sum())
df['Egységár']=df.groupby('Terméknév')['Egységár'].transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan))

print(df.loc[df['Egységár'].isna()])
df['Érték']=df['Egységár']-df['Mennyiség']
print(df.head(5))

0
0
Empty DataFrame
Columns: [Dátum, Kategórianév, Terméknév, Egységár, Mennyiség, Érték, Vevőnév, Vevő megye, Vevő város, Bolt megye, Bolt város, Boltnév]
Index: []
        Dátum Kategórianév Terméknév  Egységár  Mennyiség  Érték    Vevőnév  \
0  01/02/2015        Iroda       Tol       400        8.0  392.0  Kovács Bt
1  01/13/2015        Játék     Labda       500        6.0  494.0  Kovács Bt
2  01/23/2015        Játék     Labda       500        3.0  497.0   Nagy Kft
3  01/24/2015         Kert  Gereblye       700       -4.0  704.0   Nagy Kft
4  02/02/2015        Iroda      Toll       400        8.0  392.0  Kovács Bt

  Vevő megye Vevő város Bolt megye Bolt város Boltnév
0       Pest    Gödöllő      Heves       Eger  2. ABC
1       Pest    Gödöllő      Heves   Gyöngyös  1. ABC
2      Heves   Gyöngyös      Heves   Gyöngyös  1. ABC
3      Heves   Gyöngyös       Pest    Gödöllő  2. ABC
4       Pest    Gödöllő      Heves       Eger  2. ABC

In [107]:
df.loc[df['Egységár'].isna()]
print(df['Terméknév'].unique())

['Tol' 'Labda' 'Gereblye' 'Toll' 'creuza' 'Kapa' 'Ásó' 'Ceruza' 'cerza'
 'Kártya' 'Ugrókötél' 'Kanna' 'Füzet' 'Tolll']

In [121]:
#7. Mentsen dataframe-t Javított.csv néven, ahol az elválasztó karakter a vessző.
df['Terméknév'] = df['Terméknév'].replace(['creuza', 'cerza'], 'Ceruza')
df['Terméknév'] = df['Terméknév'].replace(['Tol', 'Tolll'], 'Toll')
print(df['Terméknév'].unique())

['Toll' 'Labda' 'Gereblye' 'Ceruza' 'Kapa' 'Ásó' 'Kártya' 'Ugrókötél'
 'Kanna' 'Füzet']

In [129]:
df.Mennyiség=df.Mennyiség.abs()
atlag_maszk=(df.Mennyiség.shift(-1)+df.Mennyiség.shift(1))/2
df.Mennyiség.loc[df['Mennyiség']>200]=atlag_maszk
df['Mennyiség'].unique()
print(df.loc[df.duplicated()])

          Dátum Kategórianév  Terméknév  Egységár  Mennyiség  Érték   Vevőnév  \
16   06/14/2015        Játék      Labda       500        9.0  491.0    Kis Bt
17   06/14/2015        Játék      Labda       500        9.0  491.0    Kis Bt
32   10/15/2015        Játék      Labda       500        8.0  492.0    Kis Bt
73   04/16/2016         Kert   Gereblye       700        7.0  693.0  Nagy Kft
113  08/23/2016         Kert      Kanna       800       12.0  788.0  Nagy Kft
145  12/11/2016        Játék      Labda       500        6.0  494.0  Szabó Rt
162  02/08/2017        Iroda      Füzet       200        8.0  192.0  Tóth Kft
176  05/02/2017         Kert       Kapa       800        7.0  793.0    Kis Bt
178  05/05/2017        Játék  Ugrókötél       800        6.0  794.0  Nagy Kft
194  07/10/2017         Kert       Kapa       800        6.0  794.0  Tóth Kft
202  08/23/2017        Iroda      Füzet       200        6.0  194.0    Kis Bt
215  10/10/2017         Kert   Gereblye       700        8.0  692.0  Tóth Kft

    Vevő megye Vevő város Bolt megye Bolt város Boltnév
16       Heves     Hatvan       Pest  Kistarcsa  2. ABC
17       Heves     Hatvan       Pest  Kistarcsa  2. ABC
32       Heves     Hatvan       Pest  Kistarcsa  2. ABC
73       Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
113      Heves   Gyöngyös      Heves   Gyöngyös  2. ABC
145       Pest      Monor      Heves   Gyöngyös  2. ABC
162      Heves       Eger      Heves   Gyöngyös  2. ABC
176      Heves     Hatvan       Pest    Gödöllő  2. ABC
178      Heves   Gyöngyös       Pest  Kistarcsa  1. ABC
194      Heves       Eger      Heves   Gyöngyös  2. ABC
202      Heves     Hatvan       Pest  Kistarcsa  2. ABC
215      Heves       Eger       Pest    Gödöllő  2. ABC

C:\Users\User\AppData\Local\Temp\ipykernel_23420\3585142550.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.Mennyiség.loc[df['Mennyiség']>200]=atlag_maszk
C:\Users\User\AppData\Local\Temp\ipykernel_23420\3585142550.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Mennyiség.loc[df['Mennyiség']>200]=atlag_maszk

In [130]:
df=df.drop_duplicates(keep='last')
print(df.loc[df.duplicated()])

Empty DataFrame
Columns: [Dátum, Kategórianév, Terméknév, Egységár, Mennyiség, Érték, Vevőnév, Vevő megye, Vevő város, Bolt megye, Bolt város, Boltnév]
Index: []

In [131]:
mentes=df.to_csv('Javitott2.csv',sep=',',encoding='ISO-8859-2')

In [132]:
mentes